easy_admin:
    design:
        menu:
            - label: 'Utilities'
              icone: 'newspaper-o'
              children:
                  - {entity: 'Poll'}
                  - {entity: 'Question'}
                  - {entity: 'Answer'}

            - label: 'Option'
              icone: 'newspaper-o'
              children:
                - {entity: 'Tag'}

    entities:
        Poll:
            class: App\Entity\Poll
            form:
              fields:
                - 'name'
                - 'passToken'
                - 'questions'
        Question:
            class: App\Entity\Question
        Answer:
            class: App\Entity\Answer
        Tag:
            class: App\Entity\Tag
            form:
              fields:
              - {property: 'name'}

