easy_admin:
    design:
        menu:
              - {entity: 'Poll', default: true}
              - {entity: 'Question'}
              - {label: 'Homepage', route: 'app_user_index', icon: 'home'}
              - {label: 'Profile', url: '/profile', icon: 'user' }
    entities:
        User:
          class: App\Entity\User
          disabled_actions: ['edit', 'delete']
          list:
            fields:
              - 'username'
              - 'email'
              - 'lastLogin'
          show:
            fields:
              - 'username'
              - 'email'
        Poll:
            class: App\Entity\Poll
            form:
              fields:
                - 'name'
                - 'passToken'
            list:
              fields:
                - 'name'
                - 'passToken'
                - 'questions'
              actions:
                - { name: 'Run', type: 'route' }

        Question:
            class: App\Entity\Question
            form:
              fields:
                - 'text'
                - { property: 'answers', type: 'collection', type_options: { entry_type: 'App\Form\AnswerEmbeddedForm', allow_delete: true, allow_add: true, by_reference: false, attr:{value: '',min: 1, max: 255 }} }
            list:
              fields:
                - 'text'
                - 'poll'
                - 'answers'
            edit:
              fields:
                - { property: 'text'}
                - { property: 'answers'}
                - { property: '-poll'}
        Answer:
            class: App\Entity\Answer


