easy_admin:
    design:
        menu:
              - {entity: 'Poll'}
              - {entity: 'Question'}
    entities:
        User:
          class: App\Entity\User
          list:
            fields:
              - 'username'
              - 'email'
              - 'lastLogin'
          edit:
            fields:
              - { property: 'username'}
              - { property: 'email'}
              - { property: 'plainPassword'}
        Poll:
            class: App\Entity\Poll
            form:
              fields:
                - 'name'
                - 'passToken'
            list:
              fields:
                - 'name'
                - 'passToken'
                - 'questions'
              actions:
                - { name: 'Run', type: 'route' }

        Question:
            class: App\Entity\Question
            form:
              fields:
                - 'text'
                - 'poll'
                - { property: 'answers', type: 'collection', type_options: { entry_type: 'App\Form\AnswerEmbeddedForm', allow_delete: true, allow_add: true, by_reference: false} }
            list:
              fields:
                - 'text'
                - 'poll'
                - 'answers'

        Answer:
            class: App\Entity\Answer


