easy_admin:

    design:
        menu:
            - label: 'Utilities'
              icone: 'newspaper-o'
              children:
                  - {entity: 'Poll'}
                  - {entity: 'Question'}
                  - {entity: 'Answer'}

            - label: 'Option'
              icone: 'newspaper-o'
              children:
                - {entity: 'Tag'}

            - label: 'User'
              icone: 'newspaper-o'

    entities:
        Poll:
            class: App\Entity\Poll
        Question:
            class: App\Entity\Question
        Answer:
            class: App\Entity\Answer
        Tag:
            class: App\Entity\Tag
            form:
              fields:
              - {property: 'name'}

