#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_admin_index:
    path: /home
    controller: App\Controller\Admin_controller::home

app_question_new:
    path: /home/question
    controller: App\Controller\QuestionController::new

app_admin_runPoll:
    path: /home/runPoll/{poll_token}
    controller: App\Controller\Admin_controller::run_poll

app_admin_setNextQuestion:
    path: /home/setNextQuestion/{poll_token}
    controller: App\Controller\Admin_controller::set_next_question

app_admin_setLastQuestion:
    path: /home/setLastQuestion/{poll_token}
    controller: App\Controller\Admin_controller::set_last_question

app_user_getPoll:
    path: /getPoll/{poll_token}
    controller: App\Controller\User_controller::get_poll

app_user_incrementPollStatistic:
    path: /incrementPollStatistic/{poll_token}
    controller: App\Controller\User_controller::increment_poll_statistic


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"