index:
    path: /
    controller: App\Controller\Admin_controller::home

app_demo_getTemplate:
    path: /demo/getTemplate
    controller: App\Controller\Demo_controller::get_template
app_demo_getHttpResponse:
    path: /demo/getHttpResponse
    controller: App\Controller\Demo_controller::get_http_response
app_demo_getRandomNumber:
    path: /demo/getRandomNumber
    controller: App\Controller\Demo_controller::get_random_number

app_admin_index:
    path: /home
    controller: App\Controller\Admin_controller::index

app_admin_createPoll:
    path: /home/createPoll
    controller: App\Controller\Admin_controller::create_poll

app_question_new:
    path: /home/question
    controller: App\Controller\QuestionController::new
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"