<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1NLnweP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1NLnweP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1NLnweP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1NLnweP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1NLnweP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1NLnweP',
    'container.build_id' => '31d40f2e',
    'container.build_time' => 1586107666,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1NLnweP');
