<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'app_demo_getTemplate' => [[], ['_controller' => 'App\\Controller\\Demo_controller::get_template'], [], [['text', '/demo/getTemplate']], [], []],
    'app_demo_getHttpResponse' => [[], ['_controller' => 'App\\Controller\\Demo_controller::get_http_response'], [], [['text', '/demo/getHttpResponse']], [], []],
    'app_demo_getRandomNumber' => [[], ['_controller' => 'App\\Controller\\Demo_controller::get_random_number'], [], [['text', '/demo/getRandomNumber']], [], []],
    'app_admin_index' => [[], ['_controller' => 'App\\Controller\\Admin_controller::index'], [], [['text', '/admin']], [], []],
    'app_admin_createPoll' => [[], ['_controller' => 'App\\Controller\\Admin_controller::create_poll'], [], [['text', '/admin/createPoll']], [], []],
    'app_user_getCurrentPoll' => [[], ['_controller' => 'App\\Controller\\User_controller::get_current_poll'], [], [['text', '/user/getCurrentPoll']], [], []],
];
